### ISSUE TITLE
Shapes can't be multiplied (Stage 2)

### ISSUE THREAD

**Issue by hilmiyafia** [oatsu-gh/enunu_training_kit#3]
Hello, I'm having this error in Stage 2:
RuntimeError: mat1 and mat2 shapes cannot be multiplied (405x203 and 221x128)

![Error](https://user-images.githubusercontent.com/56539775/135736176-2b0a6cec-3fba-4cd3-90db-efde56714d4e.JPG)

**Comment by oatsu-gh** [comment]
Pleases check that the number of "QS" in the hed file selected in config.yaml is equal to the `in_dim` in train/conf/train/timelag/model/timelag_ffn.yaml (or timelag_mdn.yaml).

**Comment by hilmiyafia** [comment]
@oatsu-gh Thank you so much! It works now. Anyway, do you have a guide to create HED file for a new language? Because somehow at Stage 4, the loss is not converging. It diverges to a really large number like 8490424320...

**Comment by oatsu-gh** [comment]
> A guide to create

I wish I could but it's too hard to me now😢

**Comment by hilmiyafia** [comment]
@oatsu-gh That's okay, thank you very much! 😊
