### ISSUE TITLE
Mistake in kana2phonemes?

### ISSUE THREAD

**Issue by causticism** [oatsu-gh/enunu_training_kit#7]
>Line 327 in kana2phonemes_002_oto2lab.table
>Line 332 in kana2phonemes_001_oto2lab.table

`ふゃ fy A` where it appears it should be `ふゃ fy a` instead.
Is this a mistake?

Edit:
I also noticed the "Edge" is before the vowel in all cases. Is this intentional?
<details><summary>Current entries</summary>

```’あ Edge a
’ア Edge A
’い Edge i
’イ Edge I
’う Edge u
’ウ Edge U
’え Edge e
’エ Edge E
’お Edge o
’オ Edge O
’ん Edge N
あ’ Edge a
ア’ Edge A
い’ Edge i
イ’ Edge I
う’ Edge u
ウ’ Edge U
え’ Edge e
エ’ Edge E
お’ Edge o
オ’ Edge O
ん’ Edge N
```
</details>
<details><summary>Expectation</summary>

```’あ Edge a
’ア Edge A
’い Edge i
’イ Edge I
’う Edge u
’ウ Edge U
’え Edge e
’エ Edge E
’お Edge o
’オ Edge O
’ん Edge N
あ’ a Edge
ア’ A Edge
い’ i Edge
イ’ I Edge
う’ u Edge
ウ’ U Edge
え’ e Edge
エ’ E Edge
お’ o Edge
オ’ O Edge
ん’ N Edge
```
</details>

Thank you.

**Comment by oatsu-gh** [comment]
Thank you reporting!

- `ふゃ fy A` shold be fixed.
- `Edge` : intentional(experimental)
